# Generated by Django 5.2 on 2025-04-30 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Legislator',
            fields=[
                ('member_id', models.CharField(help_text='OpenWatch API member ID (고유 식별자)', max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_index=True, help_text="이름 (API 'name')", max_length=50)),
                ('party', models.CharField(blank=True, help_text="정당명 (API 'partyName')", max_length=100, null=True)),
                ('gender', models.CharField(blank=True, help_text="성별 (API 'gender')", max_length=10, null=True)),
                ('reelected', models.CharField(blank=True, help_text="재선여부 (API 'reelected')", max_length=50, null=True)),
                ('electoral_district', models.CharField(blank=True, help_text="선거구 (API 'electoralDistrict')", max_length=100, null=True)),
                ('latest_age', models.IntegerField(blank=True, help_text="활동 회기 (API 'latestAge')", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openwatch_asset_id', models.BigIntegerField(blank=True, help_text='OpenWatch API 상의 자산 고유 ID', null=True, unique=True)),
                ('report_year', models.IntegerField(db_index=True, help_text='재산 신고 기준 연도')),
                ('report_month', models.IntegerField(help_text='재산 신고 기준 월', null=True)),
                ('asset_type', models.CharField(db_index=True, help_text="재산 종류 (API 'type')", max_length=100)),
                ('kind', models.CharField(blank=True, help_text="상세 종류 (API 'kind')", max_length=100, null=True)),
                ('relation', models.CharField(help_text="소유자와의 관계 (API 'relation')", max_length=50)),
                ('detail', models.TextField(help_text="재산 상세 내역 (API 'detail')")),
                ('current_valuation', models.BigIntegerField(blank=True, help_text="현재 가액 (API 'currentValuation')", null=True)),
                ('reason_for_change', models.TextField(blank=True, help_text="변동 사유 (API 'reason')", null=True)),
                ('origin_valuation', models.BigIntegerField(blank=True, help_text="최초 가액 (API 'originValuation')", null=True)),
                ('increased_amount', models.BigIntegerField(blank=True, help_text="증가액 (API 'increasedAmount')", null=True)),
                ('decreased_amount', models.BigIntegerField(blank=True, help_text="감소액 (API 'decreasedAmount')", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legislator', models.ForeignKey(help_text='해당 자산이 속한 국회의원 (nationalAssemblyMemberId를 통해 연결)', on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='core.legislator')),
            ],
            options={
                'ordering': ['-report_year', '-report_month', 'legislator__name', 'asset_type'],
            },
        ),
    ]
