# Generated by Django 5.2 on 2025-05-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('chinese_name', models.CharField(max_length=100)),
                ('birth_cd', models.BooleanField()),
                ('birth_date', models.DateField()),
                ('position', models.CharField(max_length=100)),
                ('party', models.CharField(max_length=100)),
                ('ward', models.CharField(max_length=100)),
                ('committee', models.CharField(max_length=100)),
                ('session', models.CharField(max_length=10)),
                ('gender', models.BooleanField()),
                ('tel', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('history', models.JSONField(default=list)),
                ('office', models.JSONField(default=list)),
                ('year_month', models.CharField(max_length=10)),
                ('pro_classify', models.CharField(max_length=100)),
                ('pro_relationship', models.CharField(max_length=10)),
                ('pro_kind', models.CharField(max_length=100)),
                ('pro_details', models.CharField(max_length=100)),
                ('pre_price', models.IntegerField()),
                ('inc_price', models.IntegerField()),
                ('inc_autual_price', models.IntegerField()),
                ('dec_price', models.IntegerField()),
                ('dec_actual_price', models.IntegerField()),
                ('cur_price', models.IntegerField()),
                ('change', models.CharField(max_length=100)),
                ('sum_price', models.IntegerField()),
                ('year_price', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_price', models.JSONField(default=dict)),
                ('poly_price', models.JSONField(default=dict)),
            ],
        ),
    ]
