# Generated by Django 5.2 on 2025-05-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('chinese_name', models.CharField(max_length=100)),
                ('birth_cd', models.BooleanField()),
                ('birth_date', models.DateField()),
                ('position', models.CharField(max_length=100)),
                ('party', models.CharField(max_length=100)),
                ('ward', models.CharField(max_length=100)),
                ('committee', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=10)),
                ('gender', models.BooleanField()),
                ('tel', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
