# Generated by Django 5.2 on 2025-05-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legislator',
            name='total_assets',
            field=models.BigIntegerField(default=0),
        ),
    ]
