# Generated by Django 5.2 on 2025-05-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legislator',
            name='latest_age',
            field=models.CharField(blank=True, help_text="활동 회기 (API 'latestAge')", null=True),
        ),
    ]
