# Generated by Django 5.2 on 2025-05-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('year_month', models.CharField(max_length=10)),
                ('pro_classify', models.CharField(max_length=100)),
                ('pro_relationship', models.CharField(max_length=10)),
                ('pro_kind', models.CharField(max_length=100)),
                ('pro_details', models.CharField(max_length=100)),
                ('pre_price', models.IntegerField()),
                ('inc_price', models.IntegerField()),
                ('inc_autual_price', models.IntegerField()),
                ('dec_price', models.IntegerField()),
                ('dec_actual_price', models.IntegerField()),
                ('cur_price', models.IntegerField()),
                ('change', models.CharField(max_length=100)),
                ('sum_price', models.IntegerField()),
                ('year_price', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_price', models.JSONField(default=dict)),
                ('poly_price', models.JSONField(default=dict)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='assemblymember',
            name='history',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='assemblymember',
            name='office',
            field=models.JSONField(default=list),
        ),
    ]
